---

- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Run a specific subset of tests
      command: >
        /opt/openwisp2/env/bin/python /opt/openwisp2/manage.py test --keepdb --exclude skip_prod \
            openwisp_controller.config.tests.test_selenium.TestDeviceAdmin.test_multiple_organization_templates
      changed_when: false

    - name: Check if redis-server is running
      command: systemctl status redis-server
      changed_when: false

    - name: Chcke if redis is running
      command: systemctl status redis
      changed_when: false

    - name: Check Openwisp
      block:
        - name: Check if OpenWISP is running
          uri:
            url: "https://{{ inventory_hostname }}/admin/login/?next=/admin/"
            validate_certs: false
      rescue:
        - name: Get OpenWisp log
          command: "tail -n 500 {{ openwisp2_path }}/log/*.log"
          register: openwisp_log

        - name: Show OpenWisp log
          debug:
            var: openwisp_log

    - name: Check if FreeRADIUS is listening on WPA Enterprise site ports
      shell: "netstat -tuln | grep -Eq '1822|1823|18230'"
      register: freeradius_eap_ports  # Register the output and return code
      failed_when: freeradius_eap_ports.rc
      changed_when: false
